# Generated by Django 5.2.9 on 2025-12-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('code', models.CharField(help_text='مثال: ENS, ETU, CHF_DEP...', max_length=50, unique=True, verbose_name='الرمز')),
                ('type', models.CharField(choices=[('enseignant', 'أستاذ'), ('etudiant', 'طالب'), ('admin', 'إداري'), ('personnel', 'موظف'), ('invite', 'ضيف')], default='personnel', max_length=20, verbose_name='النوع')),
                ('nom_ar', models.CharField(blank=True, default='', max_length=100, verbose_name='المنصب')),
                ('nom_fr', models.CharField(blank=True, default='', max_length=100, verbose_name='Poste (FR)')),
                ('nom_ar_mini', models.CharField(blank=True, default='', max_length=20, verbose_name='الإختصار')),
                ('nom_fr_mini', models.CharField(blank=True, default='', max_length=20, verbose_name='Abréviation (FR)')),
                ('niveau', models.PositiveSmallIntegerField(default=0, help_text='0=قاعدة، 10=إدارة عليا', verbose_name='المستوى الهرمي')),
                ('est_actif', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'منصب',
                'verbose_name_plural': 'المناصب',
                'ordering': ['-niveau', 'nom_ar'],
                'indexes': [models.Index(fields=['code'], name='commun_post_code_6dd20e_idx'), models.Index(fields=['type', 'niveau'], name='commun_post_type_f22e8f_idx')],
            },
        ),
    ]
