# Generated by Django 5.2.18 on 2026-10-06 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commun', '0001_initial'),
        ('departement', '0001_initial'),
        ('faculte', '0001_initial'),
        ('universite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='affectationposte',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affectations_postes', to='departement.departement', verbose_name='القسم / Département'),
        ),
        migrations.AddField(
            model_name='affectationposte',
            name='faculte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affectations_postes', to='faculte.faculte', verbose_name='الكلية / Faculté'),
        ),
        migrations.AddField(
            model_name='affectationposte',
            name='universite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affectations_postes', to='universite.universite', verbose_name='الجامعة / Université'),
        ),
        migrations.AddField(
            model_name='affectationposte',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_postes', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم / Utilisateur'),
        ),
        migrations.AddIndex(
            model_name='amphi',
            index=models.Index(fields=['numero'], name='commun_amph_numero_ef243e_idx'),
        ),
        migrations.AddIndex(
            model_name='anneeuniversitaire',
            index=models.Index(fields=['est_courante'], name='commun_anne_est_cou_beab78_idx'),
        ),
        migrations.AddIndex(
            model_name='anneeuniversitaire',
            index=models.Index(fields=['date_debut', 'date_fin'], name='commun_anne_date_de_41b2dd_idx'),
        ),
        migrations.AddField(
            model_name='affectationposte',
            name='annee_univ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_postes', to='commun.anneeuniversitaire', verbose_name='السنة الجامعية / Année universitaire'),
        ),
        migrations.AddIndex(
            model_name='cycle',
            index=models.Index(fields=['code'], name='commun_cycl_code_23ccb4_idx'),
        ),
        migrations.AddIndex(
            model_name='diplome',
            index=models.Index(fields=['code'], name='commun_dipl_code_05aa7e_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['code'], name='commun_grad_code_67c38e_idx'),
        ),
        migrations.AddIndex(
            model_name='groupe',
            index=models.Index(fields=['code'], name='commun_grou_code_a08073_idx'),
        ),
        migrations.AddIndex(
            model_name='groupe',
            index=models.Index(fields=['numero'], name='commun_grou_numero_0b7799_idx'),
        ),
        migrations.AddIndex(
            model_name='identification',
            index=models.Index(fields=['code'], name='commun_iden_code_fefa37_idx'),
        ),
        migrations.AddIndex(
            model_name='laboratoire',
            index=models.Index(fields=['numero'], name='commun_labo_numero_38ea2d_idx'),
        ),
        migrations.AddIndex(
            model_name='laboratoire',
            index=models.Index(fields=['type'], name='commun_labo_type_54b472_idx'),
        ),
        migrations.AddIndex(
            model_name='niveau',
            index=models.Index(fields=['code'], name='commun_nive_code_6247a5_idx'),
        ),
        migrations.AddIndex(
            model_name='parcours',
            index=models.Index(fields=['code'], name='commun_parc_code_6f5063_idx'),
        ),
        migrations.AddIndex(
            model_name='pays',
            index=models.Index(fields=['code'], name='commun_pays_code_3a008c_idx'),
        ),
        migrations.AddIndex(
            model_name='poste',
            index=models.Index(fields=['code'], name='commun_post_code_6dd20e_idx'),
        ),
        migrations.AddIndex(
            model_name='poste',
            index=models.Index(fields=['type', 'niveau'], name='commun_post_type_f22e8f_idx'),
        ),
        migrations.AddField(
            model_name='affectationposte',
            name='poste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations', to='commun.poste', verbose_name='المنصب / Poste'),
        ),
        migrations.AddField(
            model_name='postepermission',
            name='poste',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='commun.poste', verbose_name='المنصب / Poste'),
        ),
        migrations.AddField(
            model_name='reforme',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reformes', to='commun.cycle', verbose_name='الطور / Cycle'),
        ),
        migrations.AddIndex(
            model_name='salle',
            index=models.Index(fields=['numero'], name='commun_sall_numero_5a76be_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['code'], name='commun_sect_code_da1729_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['numero'], name='commun_sect_numero_19ebfe_idx'),
        ),
        migrations.AddIndex(
            model_name='semestre',
            index=models.Index(fields=['code'], name='commun_seme_code_70381c_idx'),
        ),
        migrations.AddIndex(
            model_name='semestre',
            index=models.Index(fields=['numero'], name='commun_seme_numero_8ad8d4_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['code'], name='commun_sess_code_469d6f_idx'),
        ),
        migrations.AddIndex(
            model_name='unite',
            index=models.Index(fields=['code'], name='commun_unit_code_6fb4e0_idx'),
        ),
        migrations.AddField(
            model_name='wilaya',
            name='pays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wilayas', to='commun.pays', verbose_name='البلد / Pays'),
        ),
        migrations.AddIndex(
            model_name='affectationposte',
            index=models.Index(fields=['user', 'est_actif'], name='commun_affe_user_id_542507_idx'),
        ),
        migrations.AddIndex(
            model_name='affectationposte',
            index=models.Index(fields=['poste', 'est_actif'], name='commun_affe_poste_i_2329d8_idx'),
        ),
        migrations.AddIndex(
            model_name='affectationposte',
            index=models.Index(fields=['departement', 'est_actif'], name='commun_affe_departe_644b14_idx'),
        ),
        migrations.AddIndex(
            model_name='affectationposte',
            index=models.Index(fields=['faculte', 'est_actif'], name='commun_affe_faculte_199267_idx'),
        ),
        migrations.AddIndex(
            model_name='affectationposte',
            index=models.Index(fields=['universite', 'est_actif'], name='commun_affe_univers_fb7807_idx'),
        ),
        migrations.AddIndex(
            model_name='affectationposte',
            index=models.Index(fields=['annee_univ', 'est_actif'], name='commun_affe_annee_u_554942_idx'),
        ),
        migrations.AddIndex(
            model_name='reforme',
            index=models.Index(fields=['code'], name='commun_refo_code_637465_idx'),
        ),
        migrations.AddIndex(
            model_name='wilaya',
            index=models.Index(fields=['code'], name='commun_wila_code_a58d14_idx'),
        ),
    ]
