# Generated by Django 5.2.9 on 2025-12-10 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commun', '0002_poste_observation_alter_poste_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wilaya',
            name='codePostal',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='الرمز البريدي / Code postal'),
        ),
        migrations.AddField(
            model_name='wilaya',
            name='pays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wilayas', to='commun.pays', verbose_name='البلد / Pays'),
        ),
    ]
