# Generated by Django 5.2.18 on 2026-10-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commun', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratoire',
            name='type',
            field=models.CharField(choices=[('informatique', 'إعلام آلي / Informatique'), ('physique', 'فيزياء / Physique'), ('chimie', 'كيمياء / Chimie'), ('biologie', 'بيولوجيا / Biologie'), ('geologie', 'جيولوجيا / Géologie'), ('production', 'إنتاج / Production'), ('autres', 'أخرى / Autres')], default='autres', max_length=20, verbose_name='نوع المخبر / Type'),
        ),
    ]
