# Generated by Django 5.2.18 on 2026-10-08 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commun', '0003_laboratoire_type_production'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affectationposte',
            options={'ordering': ['-poste__niveau', 'user__last_name'], 'verbose_name': 'تعيين منصب / Affectation de poste', 'verbose_name_plural': 'تعيينات المناصب / Affectations de postes'},
        ),
        migrations.AlterModelOptions(
            name='poste',
            options={'ordering': ['-niveau', 'nom_ar'], 'verbose_name': 'منصب / Poste', 'verbose_name_plural': 'المناصب / Postes'},
        ),
        migrations.AlterModelOptions(
            name='postepermission',
            options={'verbose_name': 'صلاحيات منصب / Permissions de poste', 'verbose_name_plural': 'صلاحيات المناصب / Permissions des postes'},
        ),
        migrations.AlterModelOptions(
            name='wilaya',
            options={'ordering': ['code'], 'verbose_name': 'ولاية / Wilaya', 'verbose_name_plural': 'الولايات / Wilayas'},
        ),
    ]
