# Generated by Django 5.2.9 on 2025-12-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commun', '0003_wilaya_codepostal_wilaya_pays'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identification',
            options={'ordering': ['code'], 'verbose_name': 'التعريف / Identification', 'verbose_name_plural': 'التعاريف / Identifications'},
        ),
        migrations.AlterField(
            model_name='identification',
            name='nom_ar',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='التعريف / Identification'),
        ),
    ]
