# Generated by Django 5.2.18 on 2026-10-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commun', '0004_libelles_bilingues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='الرمز / Code'),
        ),
        migrations.AlterField(
            model_name='diplome',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='الرمز / Code'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='الرمز / Code'),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='الرمز / Code'),
        ),
        migrations.AlterField(
            model_name='identification',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='الرمز / Code'),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='الرمز / Code'),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='الرمز / Code'),
        ),
        migrations.AlterField(
            model_name='pays',
            name='code',
            field=models.CharField(blank=True, help_text='Code ISO 3 lettres', max_length=3, null=True, unique=True, verbose_name='الرمز / Code'),
        ),
        migrations.AlterField(
            model_name='reforme',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='الرمز / Code'),
        ),
        migrations.AlterField(
            model_name='section',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='الرمز / Code'),
        ),
        migrations.AlterField(
            model_name='semestre',
            name='code',
            field=models.CharField(blank=True, help_text='S1, S2, etc.', max_length=10, null=True, unique=True, verbose_name='الرمز / Code'),
        ),
        migrations.AlterField(
            model_name='session',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='الرمز / Code'),
        ),
        migrations.AlterField(
            model_name='unite',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='الرمز / Code'),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='code',
            field=models.CharField(blank=True, help_text='01-69', max_length=2, null=True, unique=True, verbose_name='الرمز'),
        ),
    ]
