# Generated by Django 5.2.9 on 2025-12-10 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commun', '0002_poste_observation_alter_poste_created_at_and_more'),
        ('enseignant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Universite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء / Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل / Date de modification')),
                ('observation', models.TextField(blank=True, default='', verbose_name='الملاحظة / Observation')),
                ('code', models.CharField(help_text='Ex: USTHB, UNIV-ALG1', max_length=20, unique=True, verbose_name='الرمز / Code')),
                ('nom_ar', models.CharField(blank=True, default='', max_length=200, verbose_name='الجامعة')),
                ('nom_fr', models.CharField(blank=True, default='', max_length=200, verbose_name='Université')),
                ('sigle', models.CharField(blank=True, default='', help_text='Ex: USTHB', max_length=50, verbose_name='الاختصار / Sigle')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='universites/logos/%Y/', verbose_name='الشعار / Logo')),
                ('adresse', models.CharField(blank=True, default='', max_length=200, verbose_name='العنوان / Adresse')),
                ('telmobile', models.CharField(blank=True, default='', max_length=20, verbose_name='المحمول / Mobile')),
                ('telfix1', models.CharField(blank=True, default='', max_length=20, verbose_name='الهاتف 1 / Tél 1')),
                ('telfix2', models.CharField(blank=True, default='', max_length=20, verbose_name='الهاتف 2 / Tél 2')),
                ('fax', models.CharField(blank=True, default='', max_length=20, verbose_name='الفاكس / Fax')),
                ('email', models.EmailField(blank=True, default='', max_length=100, verbose_name='الإيميل / Email')),
                ('siteweb', models.URLField(blank=True, default='', verbose_name='الموقع / Site Web')),
                ('facebook', models.URLField(blank=True, default='', verbose_name='Facebook')),
                ('x_twitter', models.URLField(blank=True, default='', verbose_name='X (Twitter)')),
                ('linkedIn', models.URLField(blank=True, default='', verbose_name='LinkedIn')),
                ('tiktok', models.URLField(blank=True, default='', verbose_name='TikTok')),
                ('telegram', models.URLField(blank=True, default='', verbose_name='Telegram')),
                ('recteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='universite_as_recteur', to='enseignant.enseignant', verbose_name='المدير / Recteur')),
                ('vice_rect_p', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='universite_as_vice_rect_p', to='enseignant.enseignant', verbose_name='نائب المدير للبيداغوجيا / Vice-Recteur Pédagogique')),
                ('vice_rect_pg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='universite_as_vice_rect_pg', to='enseignant.enseignant', verbose_name='نائب المدير للدراسات العليا / Vice-Recteur PG')),
                ('wilaya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='universites', to='commun.wilaya', verbose_name='الولاية / Wilaya')),
            ],
            options={
                'verbose_name': 'جامعة',
                'verbose_name_plural': 'الجامعات',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء / Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل / Date de modification')),
                ('observation', models.TextField(blank=True, default='', verbose_name='الملاحظة / Observation')),
                ('code', models.CharField(help_text='Ex: ST, SNV', max_length=20, verbose_name='الرمز / Code')),
                ('nom_ar', models.CharField(blank=True, default='', max_length=200, verbose_name='الميدان')),
                ('nom_fr', models.CharField(blank=True, default='', max_length=200, verbose_name='Domaine')),
                ('universite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domaines', to='universite.universite', verbose_name='الجامعة / Université')),
            ],
            options={
                'verbose_name': 'ميدان',
                'verbose_name_plural': 'الميادين',
                'ordering': ['universite', 'code'],
            },
        ),
        migrations.AddIndex(
            model_name='universite',
            index=models.Index(fields=['code'], name='universite__code_ba0901_idx'),
        ),
        migrations.AddIndex(
            model_name='universite',
            index=models.Index(fields=['wilaya'], name='universite__wilaya__5a7c05_idx'),
        ),
        migrations.AddIndex(
            model_name='domaine',
            index=models.Index(fields=['universite', 'code'], name='universite__univers_10e5c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='domaine',
            unique_together={('code', 'universite')},
        ),
    ]
