# Generated by Django 5.2.18 on 2026-10-08 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domaine',
            options={'ordering': ['universite', 'code'], 'verbose_name': 'ميدان / Domaine', 'verbose_name_plural': 'الميادين / Domaines'},
        ),
        migrations.AlterModelOptions(
            name='universite',
            options={'ordering': ['code'], 'verbose_name': 'جامعة / Université', 'verbose_name_plural': 'الجامعات / Universités'},
        ),
    ]
