# Generated by Django 5.2.18 on 2026-10-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0002_libelles_bilingues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domaine',
            name='code',
            field=models.CharField(blank=True, help_text='Ex: ST, SNV', max_length=20, null=True, verbose_name='الرمز / Code'),
        ),
        migrations.AlterField(
            model_name='universite',
            name='code',
            field=models.CharField(blank=True, help_text='Ex: USTHB, UNIV-ALG1', max_length=20, null=True, unique=True, verbose_name='الرمز / Code'),
        ),
    ]
