[build]
builder = "RAILPACK"

[deploy]
preDeployCommand = ["python manage.py migrate --noinput"]
startCommand = "python manage.py collectstatic --noinput && gunicorn config.wsgi --bind 0.0.0.0:$PORT --workers 3 --access-logfile -"
restartPolicyType = "ON_FAILURE"
