# Generated by Django 5.1.7 on 2025-06-28 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commun', '0001_initial'),
        ('enseignant', '0001_initial'),
        ('faculte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='الملاحظة')),
                ('nom_ar', models.CharField(max_length=200, null=True, verbose_name='القسم')),
                ('nom_fr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Département')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='الكود')),
                ('sigle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sigle')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='departement_logos/', verbose_name='Logo')),
                ('telmobile', models.CharField(blank=True, max_length=50, null=True, verbose_name='المحمول 1')),
                ('telfix1', models.CharField(blank=True, max_length=50, null=True, verbose_name='الهاتف 1')),
                ('telfix2', models.CharField(blank=True, max_length=50, null=True, verbose_name='الهاتف 2')),
                ('tel3chiffre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tel 3 Chiffre')),
                ('fax', models.CharField(blank=True, max_length=50, null=True, verbose_name='الفاكس')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإيميل')),
                ('siteweb', models.CharField(blank=True, max_length=100, null=True, verbose_name='الموقع')),
                ('linkedIn', models.CharField(blank=True, max_length=100, null=True, verbose_name='LinkedIn')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook')),
                ('x_twitter', models.CharField(blank=True, max_length=100, null=True, verbose_name='X (Twitter)')),
                ('tiktok', models.CharField(blank=True, max_length=100, null=True, verbose_name='TikTok')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram')),
                ('creationALLseances', models.BooleanField(default=False, verbose_name='إنشاء جميع الدروس')),
                ('chef_dep_adj_p', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chef_dep_adj_p', to='enseignant.enseignant', verbose_name='Chef Dep. Adjoint Pédagogique')),
                ('chef_dep_adj_pg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chef_dep_adj_pg', to='enseignant.enseignant', verbose_name='Chef Dep. Adjoint Post-Graduation')),
                ('chef_departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chef_departement', to='enseignant.enseignant', verbose_name='Chef de Département')),
                ('faculte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departements_faculte', to='faculte.faculte', verbose_name='الكلية')),
            ],
            options={
                'verbose_name_plural': 'Départements',
            },
        ),
        migrations.CreateModel(
            name='NivSpeDep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departement.departement', verbose_name='القسم')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commun.niveau', verbose_name='المستوى')),
            ],
            options={
                'verbose_name': 'Niveau, Spécialité, Département',
                'verbose_name_plural': 'Niveaux, Spécialités, Départements',
            },
        ),
        migrations.CreateModel(
            name='NivSpeDep_SG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_affectation', models.CharField(choices=[], default='par_groupe', max_length=20, verbose_name='نوع التوزيع')),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='commun.groupe', verbose_name='الفوج')),
                ('niv_spe_dep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departement.nivspedep', verbose_name='Niveau, Spécialité, Département')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='commun.section', verbose_name='القطاع')),
            ],
            options={
                'verbose_name': 'Niv-Spé-Dép Section/Groupe',
                'verbose_name_plural': 'Niv-Spé-Dép Sections/Groupes',
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='الملاحظة')),
                ('nom_ar', models.CharField(blank=True, max_length=200, null=True, verbose_name='التخصص')),
                ('nom_fr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Specialite')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='الكود')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Specialites_departement', to='departement.departement', verbose_name='القسم')),
                ('identification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Specialites_identification', to='commun.identification', verbose_name='التعريف')),
                ('parcours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Specialites_parcours', to='commun.parcours', verbose_name='المسار')),
                ('reforme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Specialites_reforme', to='commun.reforme', verbose_name='الإصلاح')),
            ],
            options={
                'verbose_name_plural': 'Spécialités',
            },
        ),
        migrations.AddField(
            model_name='nivspedep',
            name='specialite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departement.specialite', verbose_name='التخصص'),
        ),
        migrations.AlterUniqueTogether(
            name='nivspedep',
            unique_together={('niveau', 'specialite', 'departement')},
        ),
    ]
