# Generated by Django 5.1.7 on 2025-06-28 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commun', '0001_initial'),
        ('departement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ar', models.CharField(max_length=100, verbose_name='المادة')),
                ('nom_fr', models.CharField(blank=True, max_length=100, verbose_name='Matière')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('coeff', models.FloatField(default=1.0, verbose_name='المعامل')),
                ('credit', models.IntegerField(default=0, verbose_name='Crédit')),
                ('niv_spe_dep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departement.nivspedep', verbose_name='المستوى')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commun.semestre', verbose_name='السداسي')),
                ('unite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='commun.unite', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'unique_together': {('code', 'niv_spe_dep')},
            },
        ),
    ]
