# Generated by Django 5.1.7 on 2025-06-28 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0002_matiere'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nivspedep',
            options={'verbose_name': 'Niv-Spe-Dep', 'verbose_name_plural': 'Niv-Spe-Dep'},
        ),
        migrations.AlterModelOptions(
            name='nivspedep_sg',
            options={'verbose_name': 'Niv-Spe-Dep-SG', 'verbose_name_plural': 'Niv-Spe-Dep-SG'},
        ),
    ]
