# Generated by Django 5.1.7 on 2025-06-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0003_alter_nivspedep_options_alter_nivspedep_sg_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivspedep_sg',
            name='type_affectation',
            field=models.CharField(choices=[('par_section', 'بالقطاع'), ('par_groupe', 'بالفوج'), ('tous_etudiants', 'جميع الطلبة')], default='par_groupe', max_length=20, verbose_name='نوع التوزيع'),
        ),
    ]
