# Generated by Django 5.1.7 on 2025-06-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0004_alter_nivspedep_sg_type_affectation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='code',
            field=models.CharField(max_length=20, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='nom_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='المادة'),
        ),
    ]
