# Generated by Django 5.1.7 on 2025-06-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0005_alter_matiere_code_alter_matiere_nom_ar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='nom_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المادة'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='nom_fr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Matière'),
        ),
    ]
