# Generated by Django 5.1.7 on 2025-06-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0006_alter_matiere_code_alter_matiere_nom_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivspedep',
            name='nbr_etudiants',
            field=models.IntegerField(default=0, verbose_name='عدد الطلبة'),
        ),
        migrations.AddField(
            model_name='nivspedep',
            name='nbr_matieres',
            field=models.IntegerField(default=0, verbose_name='عدد المواد'),
        ),
        migrations.AddField(
            model_name='nivspedep_sg',
            name='nbr_etudiants_SG',
            field=models.IntegerField(default=0, verbose_name='عدد الطلبة'),
        ),
    ]
