# Generated by Django 5.1.7 on 2025-06-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0007_nivspedep_nbr_etudiants_nivspedep_nbr_matieres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nivspedep',
            name='nbr_matieres',
        ),
        migrations.AddField(
            model_name='nivspedep',
            name='nbr_matieres_s1',
            field=models.IntegerField(default=0, verbose_name='عدد المواد السداسي 1'),
        ),
        migrations.AddField(
            model_name='nivspedep',
            name='nbr_matieres_s2',
            field=models.IntegerField(default=0, verbose_name='عدد المواد السداسي 2'),
        ),
    ]
