# Generated by Django 5.1.7 on 2025-06-30 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0008_remove_nivspedep_nbr_matieres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivspedep_sg',
            name='niv_spe_dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='NivSpeDep_SGsss_NivSpeDep', to='departement.nivspedep', verbose_name='Niveau, Spécialité, Département'),
        ),
    ]
