# Generated by Django 5.2.9 on 2025-12-10 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commun', '0003_wilaya_codepostal_wilaya_pays'),
        ('enseignant', '0001_initial'),
        ('faculte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء / Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل / Date de modification')),
                ('observation', models.TextField(blank=True, default='', verbose_name='الملاحظة / Observation')),
                ('code', models.CharField(help_text='Ex: INFO, MATH', max_length=20, unique=True, verbose_name='الرمز / Code')),
                ('nom_ar', models.CharField(blank=True, default='', max_length=200, verbose_name='القسم / Département')),
                ('nom_fr', models.CharField(blank=True, default='', max_length=200, verbose_name='Département')),
                ('sigle', models.CharField(blank=True, default='', help_text='Ex: INFO, MATH', max_length=50, verbose_name='الاختصار / Sigle')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='departements/logos/%Y/', verbose_name='الشعار / Logo')),
                ('telmobile', models.CharField(blank=True, default='', max_length=20, verbose_name='المحمول / Mobile')),
                ('telfix1', models.CharField(blank=True, default='', max_length=20, verbose_name='الهاتف 1 / Tél 1')),
                ('telfix2', models.CharField(blank=True, default='', max_length=20, verbose_name='الهاتف 2 / Tél 2')),
                ('tel3chiffre', models.CharField(blank=True, default='', help_text='Numéro interne à 3 chiffres', max_length=10, verbose_name='رقم داخلي / Tél 3 chiffres')),
                ('fax', models.CharField(blank=True, default='', max_length=20, verbose_name='الفاكس / Fax')),
                ('email', models.EmailField(blank=True, default='', max_length=100, verbose_name='الإيميل / Email')),
                ('siteweb', models.URLField(blank=True, default='', verbose_name='الموقع / Site Web')),
                ('facebook', models.URLField(blank=True, default='', verbose_name='Facebook')),
                ('x_twitter', models.URLField(blank=True, default='', verbose_name='X (Twitter)')),
                ('linkedIn', models.URLField(blank=True, default='', verbose_name='LinkedIn')),
                ('tiktok', models.URLField(blank=True, default='', verbose_name='TikTok')),
                ('telegram', models.URLField(blank=True, default='', verbose_name='Telegram')),
                ('creationALLseances', models.BooleanField(default=False, help_text='Créer automatiquement toutes les séances', verbose_name='إنشاء جميع الدروس / Création auto des séances')),
                ('chef_dep_adj_p', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departement_as_chef_adj_p', to='enseignant.enseignant', verbose_name='نائب رئيس القسم للبيداغوجيا / Chef Dep. Adjoint Pédagogique')),
                ('chef_dep_adj_pg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departement_as_chef_adj_pg', to='enseignant.enseignant', verbose_name='نائب رئيس القسم للدراسات العليا / Chef Dep. Adjoint Post-Graduation')),
                ('chef_departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departement_as_chef', to='enseignant.enseignant', verbose_name='رئيس القسم / Chef de Département')),
                ('faculte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departements', to='faculte.faculte', verbose_name='الكلية / Faculté')),
            ],
            options={
                'verbose_name': 'قسم / Département',
                'verbose_name_plural': 'أقسام / Départements',
                'ordering': ['faculte', 'code'],
            },
        ),
        migrations.CreateModel(
            name='NivSpeDep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbr_matieres_s1', models.IntegerField(default=0, verbose_name='عدد المواد السداسي 1 / Nb matières S1')),
                ('nbr_matieres_s2', models.IntegerField(default=0, verbose_name='عدد المواد السداسي 2 / Nb matières S2')),
                ('nbr_etudiants', models.IntegerField(default=0, verbose_name="عدد الطلبة / Nombre d'étudiants")),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departement.departement', verbose_name='القسم / Département')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commun.niveau', verbose_name='المستوى / Niveau')),
            ],
            options={
                'verbose_name': 'Niveau-Spécialité-Département',
                'verbose_name_plural': 'Niveaux-Spécialités-Départements',
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=20, verbose_name='الرمز / Code')),
                ('nom_ar', models.CharField(blank=True, default='', max_length=100, verbose_name='المادة / Matière')),
                ('nom_fr', models.CharField(blank=True, default='', max_length=100, verbose_name='Matière')),
                ('coeff', models.FloatField(default=1.0, verbose_name='المعامل / Coefficient')),
                ('credit', models.IntegerField(default=0, verbose_name='الرصيد / Crédit')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commun.semestre', verbose_name='السداسي / Semestre')),
                ('unite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='commun.unite', verbose_name='الوحدة / Unité')),
                ('niv_spe_dep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matieres', to='departement.nivspedep', verbose_name='المستوى / Niveau')),
            ],
            options={
                'verbose_name': 'مادة / Matière',
                'verbose_name_plural': 'مواد / Matières',
                'ordering': ['niv_spe_dep', 'semestre', 'code'],
            },
        ),
        migrations.CreateModel(
            name='NivSpeDep_SG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbr_etudiants_SG', models.IntegerField(default=0, verbose_name="عدد الطلبة / Nombre d'étudiants")),
                ('type_affectation', models.CharField(choices=[('par_section', 'بالقطاع / Par Section'), ('par_groupe', 'بالفوج / Par Groupe'), ('tous_etudiants', 'جميع الطلبة / Tous les Étudiants')], default='par_groupe', max_length=20, verbose_name="نوع التوزيع / Type d'affectation")),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='commun.groupe', verbose_name='الفوج / Groupe')),
                ('niv_spe_dep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections_groupes', to='departement.nivspedep', verbose_name='المستوى-التخصص-القسم / Niveau-Spécialité-Département')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='commun.section', verbose_name='القطاع / Section')),
            ],
            options={
                'verbose_name': 'Niv-Spe-Dep avec Section/Groupe',
                'verbose_name_plural': 'Niv-Spe-Dep avec Sections/Groupes',
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء / Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل / Date de modification')),
                ('observation', models.TextField(blank=True, default='', verbose_name='الملاحظة / Observation')),
                ('code', models.CharField(help_text='Ex: INFO-L, MATH-M', max_length=20, verbose_name='الرمز / Code')),
                ('nom_ar', models.CharField(blank=True, default='', max_length=200, verbose_name='التخصص / Spécialité')),
                ('nom_fr', models.CharField(blank=True, default='', max_length=200, verbose_name='Spécialité')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialites', to='departement.departement', verbose_name='القسم / Département')),
                ('identification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='specialites', to='commun.identification', verbose_name='التعريف / Identification')),
                ('parcours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='specialites', to='commun.parcours', verbose_name='المسار / Parcours')),
                ('reforme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='specialites', to='commun.reforme', verbose_name='الإصلاح / Réforme')),
            ],
            options={
                'verbose_name': 'تخصص / Spécialité',
                'verbose_name_plural': 'تخصصات / Spécialités',
                'ordering': ['departement', 'code'],
            },
        ),
        migrations.AddField(
            model_name='nivspedep',
            name='specialite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departement.specialite', verbose_name='التخصص / Spécialité'),
        ),
        migrations.AddIndex(
            model_name='departement',
            index=models.Index(fields=['code'], name='departement_code_e0a169_idx'),
        ),
        migrations.AddIndex(
            model_name='departement',
            index=models.Index(fields=['faculte', 'code'], name='departement_faculte_de8951_idx'),
        ),
        migrations.AddIndex(
            model_name='matiere',
            index=models.Index(fields=['niv_spe_dep', 'semestre'], name='departement_niv_spe_e73ee4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='matiere',
            unique_together={('code', 'niv_spe_dep')},
        ),
        migrations.AddIndex(
            model_name='specialite',
            index=models.Index(fields=['departement', 'code'], name='departement_departe_7e1853_idx'),
        ),
        migrations.AddIndex(
            model_name='specialite',
            index=models.Index(fields=['departement', 'reforme'], name='departement_departe_73e87c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='specialite',
            unique_together={('code', 'departement', 'reforme')},
        ),
        migrations.AddIndex(
            model_name='nivspedep',
            index=models.Index(fields=['departement', 'specialite', 'niveau'], name='departement_departe_79a5ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nivspedep',
            unique_together={('niveau', 'specialite', 'departement')},
        ),
    ]
