# Generated by Django 5.2.18 on 2026-10-08 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nivspedep',
            options={'verbose_name': 'مستوى-تخصص-قسم / Niveau-Spécialité-Département', 'verbose_name_plural': 'المستويات-التخصصات-الأقسام / Niveaux-Spécialités-Départements'},
        ),
    ]
