# Generated by Django 5.2.18 on 2026-10-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0002_libelles_bilingues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='code',
            field=models.CharField(blank=True, help_text='Ex: INFO, MATH', max_length=20, null=True, unique=True, verbose_name='الرمز / Code'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='الرمز / Code'),
        ),
        migrations.AlterField(
            model_name='specialite',
            name='code',
            field=models.CharField(blank=True, help_text='Ex: INFO-L, MATH-M', max_length=20, null=True, verbose_name='الرمز / Code'),
        ),
    ]
