# Generated by Django 5.2.18 on 2026-10-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='doit_changer_mot_de_passe',
            field=models.BooleanField(default=False, help_text="Si coché, l'utilisateur doit renouveler son mot de passe dès sa prochaine connexion.", verbose_name='يجب تغيير كلمة المرور / Doit changer le mot de passe'),
        ),
    ]
