# Generated by Django 5.2.18 on 2026-10-08 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_customuser_doit_changer_mot_de_passe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'مستخدم / Utilisateur', 'verbose_name_plural': 'المستخدمون / Utilisateurs'},
        ),
    ]
