# Generated by Django 5.2.18 on 2026-10-06 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commun', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء / Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل / Date de modification')),
                ('observation', models.TextField(blank=True, default='', verbose_name='الملاحظة / Observation')),
                ('civilite', models.CharField(blank=True, choices=[('Mr', 'السيد'), ('Mme', 'السيدة'), ('Mlle', 'الآنسة')], default='', max_length=50, verbose_name='حضرة / Civilité')),
                ('nom_fr', models.CharField(blank=True, default='', max_length=100, verbose_name='Nom')),
                ('prenom_fr', models.CharField(blank=True, default='', max_length=100, verbose_name='Prénom')),
                ('nom_ar', models.CharField(blank=True, default='', max_length=100, verbose_name='اللقب / Nom')),
                ('prenom_ar', models.CharField(blank=True, default='', max_length=100, verbose_name='الإسم / Prénom')),
                ('date_nais', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد / Date de naissance')),
                ('sex', models.CharField(blank=True, choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], default='ذكر', max_length=50, verbose_name='الجنس / Sexe')),
                ('sitfam', models.CharField(blank=True, choices=[('أعزب', 'أعزب'), ('متزوج', 'متزوج'), ('مطلق', 'مطلق'), ('أرمل', 'أرمل')], default='أعزب', max_length=50, verbose_name='الحالة العائلية / Situation familiale')),
                ('matricule', models.CharField(blank=True, help_text='Ex: ENS2024001', max_length=50, null=True, verbose_name='رقم التسجيل / Matricule')),
                ('codeIns', models.CharField(blank=True, default='', max_length=20, verbose_name="كود التسجيل / Code d'inscription")),
                ('bac_annee', models.CharField(blank=True, default='', help_text='Ex: 2010', max_length=4, verbose_name='سنة البكالوريا / Année du bac')),
                ('date_Recrut', models.DateField(blank=True, null=True, verbose_name='تاريخ الإلتحاق بالجامعة / Date de recrutement')),
                ('telmobile1', models.CharField(blank=True, default='', max_length=50, verbose_name='الهاتف المحمول 1 / Tel mobile 1')),
                ('telmobile2', models.CharField(blank=True, default='', max_length=50, verbose_name='الهاتف المحمول 2 / Tel mobile 2')),
                ('telfix', models.CharField(blank=True, default='', max_length=50, verbose_name='الهاتف الثابت / Tel fixe')),
                ('fax', models.CharField(blank=True, default='', max_length=50, verbose_name='الفاكس / Fax')),
                ('email_perso', models.EmailField(blank=True, default='', max_length=100, verbose_name='البريد الإلكتروني الشخصي / E-mail personnel')),
                ('email_prof', models.EmailField(blank=True, default='', max_length=100, verbose_name='البريد الإلكتروني المهني / E-mail professionnel')),
                ('adresse', models.CharField(blank=True, default='', max_length=200, verbose_name='العنوان / Adresse')),
                ('specialite_ar', models.CharField(blank=True, default='', max_length=100, verbose_name='التخصص / Spécialité')),
                ('specialite_fr', models.CharField(blank=True, default='', max_length=100, verbose_name='Spécialité')),
                ('inscritProgres', models.BooleanField(default=False, verbose_name='مسجل بمنصة PROGRES / Inscrit PROGRES')),
                ('inscritMoodle', models.BooleanField(default=False, verbose_name='مسجل بمنصة MOODLE / Inscrit MOODLE')),
                ('inscritSNDL', models.BooleanField(default=False, verbose_name='مسجل بمنصة SNDL / Inscrit SNDL')),
                ('googlescholar', models.URLField(blank=True, default='', help_text='URL du profil Google Scholar', verbose_name='Google Scholar')),
                ('researchgate', models.URLField(blank=True, default='', help_text='URL du profil ResearchGate', verbose_name='Research Gate')),
                ('orcid_id', models.CharField(blank=True, default='', help_text='Ex: 0000-0002-1234-5678', max_length=100, verbose_name='ORCID iD')),
                ('linkedIn', models.URLField(blank=True, default='', verbose_name='LinkedIn')),
                ('facebook', models.URLField(blank=True, default='', verbose_name='Facebook')),
                ('x_twitter', models.URLField(blank=True, default='', verbose_name='X (Twitter)')),
                ('tiktok', models.URLField(blank=True, default='', verbose_name='TikTok')),
                ('telegram', models.URLField(blank=True, default='', verbose_name='Telegram')),
                ('vacAcademique', models.BooleanField(default=False, verbose_name='عطلة أكاديمية / Vacances académiques')),
                ('maladie', models.BooleanField(default=False, verbose_name='عطلة مرضية / Congé maladie')),
                ('est_inscrit', models.BooleanField(default=True, verbose_name='مسجل بمنصة Inscrit sur UNIV')),
                ('scholar_publications_count', models.IntegerField(default=0, verbose_name='عدد المنشورات / Nombre de publications')),
                ('scholar_citations_count', models.IntegerField(default=0, verbose_name='عدد الاستشهادات / Nombre de citations')),
                ('scholar_h_index', models.IntegerField(default=0, verbose_name='H-index')),
                ('scholar_i10_index', models.IntegerField(default=0, verbose_name='i10-index')),
                ('scholar_last_update', models.DateTimeField(blank=True, null=True, verbose_name='آخر تحديث / Dernière mise à jour')),
                ('diplome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enseignants_diplome', to='commun.diplome', verbose_name='الدبلوم / Diplôme')),
                ('grade', models.ForeignKey(blank=True, help_text='Ex: Professeur, MCA, MCB, MAA, MAB', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enseignants_grade', to='commun.grade', verbose_name='الرتبة / Grade')),
                ('user', models.OneToOneField(blank=True, help_text='Compte utilisateur lié à cet enseignant', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enseignant_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم / Utilisateur')),
                ('wilaya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enseignants_wilaya', to='commun.wilaya', verbose_name='الولاية / Wilaya')),
            ],
            options={
                'verbose_name': 'أستاذ / Enseignant',
                'verbose_name_plural': 'الأساتذة / Enseignants',
                'ordering': ['nom_ar', 'prenom_ar'],
                'indexes': [models.Index(fields=['matricule'], name='enseignant__matricu_6d6554_idx'), models.Index(fields=['user'], name='enseignant__user_id_a25c6f_idx'), models.Index(fields=['grade'], name='enseignant__grade_i_1fb60e_idx'), models.Index(fields=['wilaya'], name='enseignant__wilaya__eb7ceb_idx')],
            },
        ),
    ]
