# Generated by Django 5.2.9 on 2025-12-10 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء / Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل / Date de modification')),
                ('observation', models.TextField(blank=True, default='', verbose_name='الملاحظة / Observation')),
                ('matricule', models.CharField(help_text='Ex: ENS2024001', max_length=20, unique=True, verbose_name='المتريكول / Matricule')),
                ('nom_ar', models.CharField(blank=True, default='', max_length=100, verbose_name='اللقب / Nom')),
                ('nom_fr', models.CharField(blank=True, default='', max_length=100, verbose_name='Nom')),
                ('prenom_ar', models.CharField(blank=True, default='', max_length=100, verbose_name='الاسم / Prénom')),
                ('prenom_fr', models.CharField(blank=True, default='', max_length=100, verbose_name='Prénom')),
                ('grade', models.CharField(blank=True, default='', help_text='Ex: Professeur, MCA, MCB, MAA, MAB', max_length=50, verbose_name='الرتبة / Grade')),
                ('email_pro', models.EmailField(blank=True, default='', max_length=100, verbose_name='البريد الإلكتروني المهني / Email professionnel')),
                ('telephone_pro', models.CharField(blank=True, default='', max_length=20, verbose_name='الهاتف المهني / Téléphone professionnel')),
                ('bureau', models.CharField(blank=True, default='', help_text='Ex: A201, Bloc B - Étage 3', max_length=50, verbose_name='المكتب / Bureau')),
                ('est_actif', models.BooleanField(default=True, verbose_name='نشط / Actif')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enseignant', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم / Utilisateur')),
            ],
            options={
                'verbose_name': 'أستاذ / Enseignant',
                'verbose_name_plural': 'الأساتذة / Enseignants',
                'ordering': ['nom_ar', 'prenom_ar'],
                'indexes': [models.Index(fields=['matricule'], name='enseignant__matricu_6d6554_idx'), models.Index(fields=['user'], name='enseignant__user_id_a25c6f_idx'), models.Index(fields=['est_actif'], name='enseignant__est_act_fa468e_idx')],
            },
        ),
    ]
