# Generated by Django 5.2.9 on 2025-12-10 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commun', '0004_alter_identification_options_and_more'),
        ('enseignant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='enseignant',
            name='enseignant__est_act_fa468e_idx',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='bureau',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='email_pro',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='est_actif',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='telephone_pro',
        ),
        migrations.AddField(
            model_name='enseignant',
            name='adresse',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='العنوان / Adresse'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='bac_annee',
            field=models.CharField(blank=True, default='', help_text='Ex: 2010', max_length=4, verbose_name='سنة البكالوريا / Année du bac'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='civilite',
            field=models.CharField(blank=True, choices=[('Mr', 'السيد'), ('Mme', 'السيدة'), ('Mlle', 'الآنسة')], default='', max_length=50, verbose_name='حضرة / Civilité'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='codeIns',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name="كود التسجيل / Code d'inscription"),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='date_Recrut',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الإلتحاق بالجامعة / Date de recrutement'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='date_nais',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد / Date de naissance'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='diplome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enseignants_diplome', to='commun.diplome', verbose_name='الدبلوم / Diplôme'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='email_perso',
            field=models.EmailField(blank=True, default='', max_length=100, verbose_name='البريد الإلكتروني الشخصي / E-mail personnel'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='email_prof',
            field=models.EmailField(blank=True, default='', max_length=100, verbose_name='البريد الإلكتروني المهني / E-mail professionnel'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='facebook',
            field=models.URLField(blank=True, default='', verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='fax',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='الفاكس / Fax'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='googlescholar',
            field=models.URLField(blank=True, default='', help_text='URL du profil Google Scholar', verbose_name='Google Scholar'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='inscritMoodle',
            field=models.BooleanField(default=False, verbose_name='مسجل بمنصة MOODLE / Inscrit MOODLE'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='inscritProgres',
            field=models.BooleanField(default=False, verbose_name='مسجل بمنصة PROGRES / Inscrit PROGRES'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='inscritSNDL',
            field=models.BooleanField(default=False, verbose_name='مسجل بمنصة SNDL / Inscrit SNDL'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='linkedIn',
            field=models.URLField(blank=True, default='', verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='maladie',
            field=models.BooleanField(default=False, verbose_name='عطلة مرضية / Congé maladie'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='orcid_id',
            field=models.CharField(blank=True, default='', help_text='Ex: 0000-0002-1234-5678', max_length=100, verbose_name='ORCID iD'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='researchgate',
            field=models.URLField(blank=True, default='', help_text='URL du profil ResearchGate', verbose_name='Research Gate'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='scholar_citations_count',
            field=models.IntegerField(default=0, verbose_name='عدد الاستشهادات / Nombre de citations'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='scholar_h_index',
            field=models.IntegerField(default=0, verbose_name='H-index'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='scholar_i10_index',
            field=models.IntegerField(default=0, verbose_name='i10-index'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='scholar_last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر تحديث / Dernière mise à jour'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='scholar_publications_count',
            field=models.IntegerField(default=0, verbose_name='عدد المنشورات / Nombre de publications'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='sex',
            field=models.CharField(blank=True, choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], default='ذكر', max_length=50, verbose_name='الجنس / Sexe'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='sitfam',
            field=models.CharField(blank=True, choices=[('أعزب', 'أعزب'), ('متزوج', 'متزوج'), ('مطلق', 'مطلق'), ('أرمل', 'أرمل')], default='أعزب', max_length=50, verbose_name='الحالة العائلية / Situation familiale'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='specialite_ar',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='التخصص / Spécialité'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='specialite_fr',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Spécialité'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='telegram',
            field=models.URLField(blank=True, default='', verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='telfix',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='الهاتف الثابت / Tel fixe'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='telmobile1',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='الهاتف المحمول 1 / Tel mobile 1'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='telmobile2',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='الهاتف المحمول 2 / Tel mobile 2'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='tiktok',
            field=models.URLField(blank=True, default='', verbose_name='TikTok'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='vacAcademique',
            field=models.BooleanField(default=False, verbose_name='عطلة أكاديمية / Vacances académiques'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='wilaya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enseignants_wilaya', to='commun.wilaya', verbose_name='الولاية / Wilaya'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='x_twitter',
            field=models.URLField(blank=True, default='', verbose_name='X (Twitter)'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='grade',
            field=models.ForeignKey(blank=True, help_text='Ex: Professeur, MCA, MCB, MAA, MAB', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enseignants_grade', to='commun.grade', verbose_name='الرتبة / Grade'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='matricule',
            field=models.CharField(help_text='Ex: ENS2024001', max_length=50, unique=True, verbose_name='رقم التسجيل / Matricule'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='prenom_ar',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='الإسم / Prénom'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='user',
            field=models.OneToOneField(help_text='Compte utilisateur lié à cet enseignant', limit_choices_to={'poste_principal__type': 'enseignant'}, on_delete=django.db.models.deletion.CASCADE, related_name='enseignant_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم / Utilisateur'),
        ),
        migrations.AddIndex(
            model_name='enseignant',
            index=models.Index(fields=['grade'], name='enseignant__grade_i_1fb60e_idx'),
        ),
        migrations.AddIndex(
            model_name='enseignant',
            index=models.Index(fields=['wilaya'], name='enseignant__wilaya__eb7ceb_idx'),
        ),
    ]
