# Generated by Django 5.2.18 on 2026-10-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='specialite_ar',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='التخصص'),
        ),
    ]
