# Generated by Django 5.2.9 on 2025-12-10 22:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commun', '0004_alter_identification_options_and_more'),
        ('enseignant', '0002_remove_enseignant_enseignant__est_act_fa468e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='est_actif',
            field=models.BooleanField(default=True, verbose_name='نشط / Actif'),
        ),
        migrations.AddIndex(
            model_name='enseignant',
            index=models.Index(fields=['est_actif'], name='enseignant__est_act_fa468e_idx'),
        ),
    ]
