# Generated by Django 5.2.9 on 2025-12-10 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignant', '0003_enseignant_est_actif_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Compte utilisateur lié à cet enseignant', limit_choices_to={'poste_principal__type': 'enseignant'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enseignant_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم / Utilisateur'),
        ),
    ]
