# Generated by Django 5.2.9 on 2025-12-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignant', '0004_alter_enseignant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='est_inscrit',
            field=models.BooleanField(default=True, verbose_name='مسجل بمنصة UNIV / Inscrit sur plateforme UNIV'),
        ),
    ]
