# Generated by Django 5.2.9 on 2025-12-10 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enseignant', '0005_enseignant_est_inscrit'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='enseignant',
            name='enseignant__est_act_fa468e_idx',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='est_actif',
        ),
    ]
