# Generated by Django 5.2.9 on 2025-12-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignant', '0006_remove_enseignant_enseignant__est_act_fa468e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='est_inscrit',
            field=models.BooleanField(default=True, verbose_name='مسجل بمنصة UNIV / Inscrit sur UNIV'),
        ),
    ]
