# Generated by Django 5.2.9 on 2025-12-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignant', '0007_alter_enseignant_est_inscrit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='est_inscrit',
            field=models.BooleanField(default=True, verbose_name='مسجل بمنصة Inscrit sur UNIV'),
        ),
    ]
