# Generated by Django 5.2.18 on 2026-10-06 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء / Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل / Date de modification')),
                ('observation', models.TextField(blank=True, default='', verbose_name='الملاحظة / Observation')),
                ('code', models.CharField(help_text='Ex: FSI, FSNV', max_length=20, unique=True, verbose_name='الرمز / Code')),
                ('nom_ar', models.CharField(blank=True, default='', max_length=200, verbose_name='الكلية / Faculté')),
                ('nom_fr', models.CharField(blank=True, default='', max_length=200, verbose_name='Faculté')),
                ('sigle', models.CharField(blank=True, default='', help_text='Ex: FSI, FSNV', max_length=50, verbose_name='الاختصار / Sigle')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='facultes/logos/%Y/', verbose_name='الشعار / Logo')),
                ('adresse', models.CharField(blank=True, default='', max_length=200, verbose_name='العنوان / Adresse')),
                ('telmobile', models.CharField(blank=True, default='', max_length=20, verbose_name='المحمول / Mobile')),
                ('telfix1', models.CharField(blank=True, default='', max_length=20, verbose_name='الهاتف 1 / Tél 1')),
                ('telfix2', models.CharField(blank=True, default='', max_length=20, verbose_name='الهاتف 2 / Tél 2')),
                ('tel3chiffre', models.CharField(blank=True, default='', help_text='Numéro interne à 3 chiffres', max_length=10, verbose_name='رقم داخلي / Tél 3 chiffres')),
                ('fax', models.CharField(blank=True, default='', max_length=20, verbose_name='الفاكس / Fax')),
                ('email', models.EmailField(blank=True, default='', max_length=100, verbose_name='الإيميل / Email')),
                ('siteweb', models.URLField(blank=True, default='', verbose_name='الموقع / Site Web')),
                ('facebook', models.URLField(blank=True, default='', verbose_name='Facebook')),
                ('x_twitter', models.URLField(blank=True, default='', verbose_name='X (Twitter)')),
                ('linkedIn', models.URLField(blank=True, default='', verbose_name='LinkedIn')),
                ('tikTok', models.URLField(blank=True, default='', verbose_name='TikTok')),
                ('telegram', models.URLField(blank=True, default='', verbose_name='Telegram')),
                ('universite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facultes', to='universite.universite', verbose_name='الجامعة / Université')),
            ],
            options={
                'verbose_name': 'كلية / Faculté',
                'verbose_name_plural': 'كليات / Facultés',
                'ordering': ['universite', 'code'],
                'indexes': [models.Index(fields=['code'], name='faculte_fac_code_7775d1_idx'), models.Index(fields=['universite', 'code'], name='faculte_fac_univers_e822cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء / Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل / Date de modification')),
                ('observation', models.TextField(blank=True, default='', verbose_name='الملاحظة / Observation')),
                ('code', models.CharField(help_text='Ex: MI, INFO', max_length=20, verbose_name='الرمز / Code')),
                ('nom_ar', models.CharField(blank=True, default='', max_length=200, verbose_name='الشعبة / Filière')),
                ('nom_fr', models.CharField(blank=True, default='', max_length=200, verbose_name='Filière')),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filieres', to='universite.domaine', verbose_name='الميدان / Domaine')),
            ],
            options={
                'verbose_name': 'شعبة / Filière',
                'verbose_name_plural': 'شعب / Filières',
                'ordering': ['domaine', 'code'],
                'indexes': [models.Index(fields=['domaine', 'code'], name='faculte_fil_domaine_cd46e9_idx')],
                'unique_together': {('code', 'domaine')},
            },
        ),
    ]
