# Generated by Django 5.2.18 on 2026-10-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculte',
            name='code',
            field=models.CharField(blank=True, help_text='Ex: FSI, FSNV', max_length=20, null=True, unique=True, verbose_name='الرمز / Code'),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='code',
            field=models.CharField(blank=True, help_text='Ex: MI, INFO', max_length=20, null=True, verbose_name='الرمز / Code'),
        ),
    ]
