# Generated by Django 5.2.9 on 2025-12-10 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commun', '0004_alter_identification_options_and_more'),
        ('departement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء / Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل / Date de modification')),
                ('observation', models.TextField(blank=True, default='', verbose_name='الملاحظة / Observation')),
                ('civilite', models.CharField(choices=[('Mr', 'السيد'), ('Mme', 'السيدة'), ('Mlle', 'الآنسة')], default='Mr', max_length=10, verbose_name='حضرة / Civilité')),
                ('nom_ar', models.CharField(blank=True, default='', max_length=100, verbose_name='اللقب / Nom')),
                ('prenom_ar', models.CharField(blank=True, default='', max_length=100, verbose_name='الإسم / Prénom')),
                ('nom_fr', models.CharField(blank=True, default='', max_length=100, verbose_name='Nom')),
                ('prenom_fr', models.CharField(blank=True, default='', max_length=100, verbose_name='Prénom')),
                ('date_nais', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد / Date de naissance')),
                ('sexe', models.CharField(choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], default='ذكر', max_length=10, verbose_name='الجنس / Sexe')),
                ('sit_fam', models.CharField(choices=[('C', 'أعزب'), ('M', 'متزوج'), ('D', 'مطلق'), ('V', 'أرمل')], default='C', max_length=10, verbose_name='الحالة العائلية / Situation familiale')),
                ('matricule', models.CharField(help_text='Ex: ETU2024001', max_length=50, unique=True, verbose_name='الرقم التسلسلي / Matricule')),
                ('num_ins', models.CharField(help_text="Numéro d'inscription national", max_length=30, unique=True, verbose_name="رقم التسجيل / Numéro d'inscription")),
                ('bac_annee', models.CharField(blank=True, default='', help_text='Ex: 2020', max_length=4, verbose_name='سنة البكالوريا / Année du bac')),
                ('delegue', models.BooleanField(default=False, verbose_name='مندوب الطلبة / Étudiant délégué')),
                ('tel_mobile1', models.CharField(blank=True, default='', max_length=20, verbose_name='الهاتف المحمول 1 / Tel mobile 1')),
                ('tel_mobile2', models.CharField(blank=True, default='', max_length=20, verbose_name='الهاتف المحمول 2 / Tel mobile 2')),
                ('tel_fix', models.CharField(blank=True, default='', max_length=20, verbose_name='الهاتف الثابت / Tel fixe')),
                ('fax', models.CharField(blank=True, default='', max_length=20, verbose_name='الفاكس / Fax')),
                ('email_perso', models.EmailField(blank=True, default='', max_length=100, verbose_name='البريد الإلكتروني الشخصي / E-mail personnel')),
                ('email_prof', models.EmailField(blank=True, default='', max_length=100, verbose_name='البريد الإلكتروني المهني / E-mail professionnel')),
                ('adresse', models.CharField(blank=True, default='', max_length=200, verbose_name='العنوان / Adresse')),
                ('inscrit_progres', models.BooleanField(default=False, verbose_name='مسجل بمنصة PROGRES / Inscrit PROGRES')),
                ('inscrit_moodle', models.BooleanField(default=False, verbose_name='مسجل بمنصة MOODLE / Inscrit MOODLE')),
                ('inscrit_sndl', models.BooleanField(default=False, verbose_name='مسجل بمنصة SNDL / Inscrit SNDL')),
                ('inscrit_univ', models.BooleanField(default=False, verbose_name='مسجل بمنصة الجامعة / Inscrit plateforme universitaire')),
                ('google_scholar', models.URLField(blank=True, default='', help_text='URL du profil Google Scholar', verbose_name='Google Scholar')),
                ('researchgate', models.URLField(blank=True, default='', help_text='URL du profil ResearchGate', verbose_name='Research Gate')),
                ('orcid_id', models.CharField(blank=True, default='', help_text='Ex: 0000-0002-1234-5678', max_length=100, verbose_name='ORCID iD')),
                ('linkedin', models.URLField(blank=True, default='', verbose_name='LinkedIn')),
                ('facebook', models.URLField(blank=True, default='', verbose_name='Facebook')),
                ('x_twitter', models.URLField(blank=True, default='', verbose_name='X (Twitter)')),
                ('tiktok', models.URLField(blank=True, default='', verbose_name='TikTok')),
                ('telegram', models.URLField(blank=True, default='', verbose_name='Telegram')),
                ('en_vac_aca', models.BooleanField(default=False, verbose_name='عطلة أكاديمية / Vacances académiques')),
                ('en_maladie', models.BooleanField(default=False, verbose_name='عطلة مرضية / Congé maladie')),
                ('est_actif', models.BooleanField(default=True, verbose_name='نشط / Actif')),
                ('niv_spe_dep_sg', models.ForeignKey(help_text='Niveau, Spécialité, Département, Section et Groupe', on_delete=django.db.models.deletion.PROTECT, related_name='etudiants', to='departement.nivspedep_sg', verbose_name='المستوى، التخصص، القسم، والفوج / Niveau-Spé-Dép-SG')),
                ('user', models.OneToOneField(blank=True, help_text='Compte utilisateur lié à cet étudiant', limit_choices_to={'poste_principal__type': 'etudiant'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etudiant_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم / Utilisateur')),
                ('wilaya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='etudiants_wilaya', to='commun.wilaya', verbose_name='الولاية / Wilaya')),
            ],
            options={
                'verbose_name': 'طالب / Étudiant',
                'verbose_name_plural': 'الطلبة / Étudiants',
                'ordering': ['nom_ar', 'prenom_ar'],
                'indexes': [models.Index(fields=['matricule'], name='etudiant_et_matricu_d0a09e_idx'), models.Index(fields=['num_ins'], name='etudiant_et_num_ins_fdb3bb_idx'), models.Index(fields=['user'], name='etudiant_et_user_id_41b8a8_idx'), models.Index(fields=['niv_spe_dep_sg'], name='etudiant_et_niv_spe_d4b328_idx'), models.Index(fields=['wilaya'], name='etudiant_et_wilaya__2b9731_idx'), models.Index(fields=['est_actif'], name='etudiant_et_est_act_b452a0_idx')],
            },
        ),
    ]
