# Generated by Django 5.2.9 on 2025-12-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='inscrit_univ',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='est_inscrit',
            field=models.BooleanField(default=True, verbose_name='مسجل بمنصة UNIV / Inscrit sur plateforme UNIV'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='est_actif',
            field=models.BooleanField(default=False, verbose_name='نشط / Actif'),
        ),
    ]
