# Generated by Django 5.2.9 on 2025-12-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0002_remove_etudiant_inscrit_univ_etudiant_est_inscrit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='est_inscrit',
            field=models.BooleanField(default=True, verbose_name='مسجل بمنصة UNIV / Inscrit sur UNIV'),
        ),
    ]
