# Generated by Django 5.2.9 on 2025-12-10 23:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commun', '0004_alter_identification_options_and_more'),
        ('departement', '0001_initial'),
        ('enseignant', '0004_alter_enseignant_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ens_Dep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء / Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل / Date de modification')),
                ('observation', models.TextField(blank=True, default='', verbose_name='الملاحظة / Observation')),
                ('date_affectation', models.DateField(default=django.utils.timezone.now, verbose_name="تاريخ الإنتساب / Date d'affectation")),
                ('statut', models.CharField(choices=[('Permanent', 'مرسّم'), ('Permanent & Vacataire', 'مرسّم و مؤقت'), ('Vacataire', 'مؤقت'), ('Associe', 'مشارك'), ('Doctorant', 'طالب دكتوراه')], default='Permanent', max_length=50, verbose_name="حالة الأستاذ / Statut de l'enseignant")),
                ('est_inscrit', models.BooleanField(default=False, verbose_name='مسجل بمنصة UNIV / Inscrit sur plateforme UNIV')),
                ('semestre_1', models.BooleanField(default=True, verbose_name='السداسي الأول / Semestre 1')),
                ('semestre_2', models.BooleanField(default=True, verbose_name='السداسي الثاني / Semestre 2')),
                ('nbrClas_ALL_Dep_S1', models.PositiveSmallIntegerField(default=0, verbose_name='عدد الحصص الكلي - س1 / Nb total séances S1')),
                ('nbrClas_in_Dep_S1', models.PositiveSmallIntegerField(default=0, verbose_name='عدد الحصص داخل القسم - س1 / Nb séances dans dép. S1')),
                ('nbrClas_Cours_in_Dep_S1', models.PositiveSmallIntegerField(default=0, verbose_name='عدد حصص المحاضرات داخل القسم - س1 / Nb cours dans dép. S1')),
                ('nbrClas_TD_in_Dep_S1', models.PositiveSmallIntegerField(default=0, verbose_name='عدد حصص الأعمال الموجهة داخل القسم - س1 / Nb TD dans dép. S1')),
                ('nbrClas_TP_in_Dep_S1', models.PositiveSmallIntegerField(default=0, verbose_name='عدد حصص الأعمال التطبيقية داخل القسم - س1 / Nb TP dans dép. S1')),
                ('nbrClas_SS_in_Dep_S1', models.PositiveSmallIntegerField(default=0, verbose_name='عدد حصص الأعمال الشخصية داخل القسم - س1 / Nb travail personnel dans dép. S1')),
                ('nbrClas_out_Dep_S1', models.PositiveSmallIntegerField(default=0, verbose_name='عدد الحصص خارج القسم - س1 / Nb séances hors dép. S1')),
                ('nbrClas_Cours_out_Dep_S1', models.PositiveSmallIntegerField(default=0, verbose_name='عدد حصص المحاضرات خارج القسم - س1 / Nb cours hors dép. S1')),
                ('nbrClas_TD_out_Dep_S1', models.PositiveSmallIntegerField(default=0, verbose_name='عدد حصص الأعمال الموجهة خارج القسم - س1 / Nb TD hors dép. S1')),
                ('nbrClas_TP_out_Dep_S1', models.PositiveSmallIntegerField(default=0, verbose_name='عدد حصص الأعمال التطبيقية خارج القسم - س1 / Nb TP hors dép. S1')),
                ('nbrClas_SS_out_Dep_S1', models.PositiveSmallIntegerField(default=0, verbose_name='عدد حصص الأعمال الشخصية خارج القسم - س1 / Nb travail personnel hors dép. S1')),
                ('nbrJour_in_Dep_S1', models.PositiveSmallIntegerField(default=0, verbose_name='عدد الأيام داخل القسم - س1 / Nb jours dans dép. S1')),
                ('volHor_in_Dep_S1', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='الحجم الساعي داخل القسم - س1 / Vol. horaire dans dép. S1')),
                ('volHor_out_Dep_S1', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='الحجم الساعي خارج القسم - س1 / Vol. horaire hors dép. S1')),
                ('taux_min_S1', models.IntegerField(default=0, verbose_name='أقل نسبة تقدم - س1 / Taux min progression S1')),
                ('taux_moyen_S1', models.FloatField(default=0.0, verbose_name='متوسط نسبة التقدم - س1 / Taux moyen progression S1')),
                ('moodle_percentage_S1', models.FloatField(default=0.0, verbose_name='نسبة النشر على Moodle - س1 / Pourcentage Moodle S1')),
                ('nbrClas_ALL_Dep_S2', models.PositiveSmallIntegerField(default=0, verbose_name='عدد الحصص الكلي - س2 / Nb total séances S2')),
                ('nbrClas_in_Dep_S2', models.PositiveSmallIntegerField(default=0, verbose_name='عدد الحصص داخل القسم - س2 / Nb séances dans dép. S2')),
                ('nbrClas_Cours_in_Dep_S2', models.PositiveSmallIntegerField(default=0, verbose_name='عدد حصص المحاضرات داخل القسم - س2 / Nb cours dans dép. S2')),
                ('nbrClas_TD_in_Dep_S2', models.PositiveSmallIntegerField(default=0, verbose_name='عدد حصص الأعمال الموجهة داخل القسم - س2 / Nb TD dans dép. S2')),
                ('nbrClas_TP_in_Dep_S2', models.PositiveSmallIntegerField(default=0, verbose_name='عدد حصص الأعمال التطبيقية داخل القسم - س2 / Nb TP dans dép. S2')),
                ('nbrClas_SS_in_Dep_S2', models.PositiveSmallIntegerField(default=0, verbose_name='عدد حصص الأعمال الشخصية داخل القسم - س2 / Nb travail personnel dans dép. S2')),
                ('nbrClas_out_Dep_S2', models.PositiveSmallIntegerField(default=0, verbose_name='عدد الحصص خارج القسم - س2 / Nb séances hors dép. S2')),
                ('nbrClas_Cours_out_Dep_S2', models.PositiveSmallIntegerField(default=0, verbose_name='عدد حصص المحاضرات خارج القسم - س2 / Nb cours hors dép. S2')),
                ('nbrClas_TD_out_Dep_S2', models.PositiveSmallIntegerField(default=0, verbose_name='عدد حصص الأعمال الموجهة خارج القسم - س2 / Nb TD hors dép. S2')),
                ('nbrClas_TP_out_Dep_S2', models.PositiveSmallIntegerField(default=0, verbose_name='عدد حصص الأعمال التطبيقية خارج القسم - س2 / Nb TP hors dép. S2')),
                ('nbrClas_SS_out_Dep_S2', models.PositiveSmallIntegerField(default=0, verbose_name='عدد حصص الأعمال الشخصية خارج القسم - س2 / Nb travail personnel hors dép. S2')),
                ('nbrJour_in_Dep_S2', models.PositiveSmallIntegerField(default=0, verbose_name='عدد الأيام داخل القسم - س2 / Nb jours dans dép. S2')),
                ('volHor_in_Dep_S2', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='الحجم الساعي داخل القسم - س2 / Vol. horaire dans dép. S2')),
                ('volHor_out_Dep_S2', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='الحجم الساعي خارج القسم - س2 / Vol. horaire hors dép. S2')),
                ('taux_min_S2', models.IntegerField(default=0, verbose_name='أقل نسبة تقدم - س2 / Taux min progression S2')),
                ('taux_moyen_S2', models.FloatField(default=0.0, verbose_name='متوسط نسبة التقدم - س2 / Taux moyen progression S2')),
                ('moodle_percentage_S2', models.FloatField(default=0.0, verbose_name='نسبة النشر على Moodle - س2 / Pourcentage Moodle S2')),
                ('annee_univ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_ens_dep', to='commun.anneeuniversitaire', verbose_name='السنة الجامعية / Année universitaire')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_enseignant', to='departement.departement', verbose_name='القسم / Département')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_departement', to='enseignant.enseignant', verbose_name='الأستاذ / Enseignant')),
            ],
            options={
                'verbose_name': 'إنتساب أستاذ-قسم / Affectation Enseignant-Département',
                'verbose_name_plural': 'إنتسابات أستاذ-قسم / Affectations Enseignant-Département',
                'ordering': ['-annee_univ__date_debut', 'departement__code', 'enseignant__nom_ar'],
                'indexes': [models.Index(fields=['enseignant', 'annee_univ'], name='affectation_enseign_7b89b9_idx'), models.Index(fields=['departement', 'annee_univ'], name='affectation_departe_e07f6a_idx'), models.Index(fields=['statut'], name='affectation_statut_d1c688_idx')],
                'unique_together': {('enseignant', 'departement', 'annee_univ')},
            },
        ),
    ]
