# Generated by Django 5.2.9 on 2025-12-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affectation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ens_dep',
            name='est_actif',
            field=models.BooleanField(default=True, verbose_name='نشط / Actif'),
        ),
    ]
