# Generated by Django 5.2.18 on 2026-10-06 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affectation', '0001_initial'),
        ('commun', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('departement', '0001_initial'),
        ('enseignant', '0001_initial'),
        ('etudiant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abs_etu_seance',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absences_etudiant', to='etudiant.etudiant', verbose_name='الطالب / Étudiant'),
        ),
        migrations.AddField(
            model_name='amphi_dep',
            name='amphi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_departement', to='commun.amphi', verbose_name='المدرج / Amphithéâtre'),
        ),
        migrations.AddField(
            model_name='amphi_dep',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_amphi', to='departement.departement', verbose_name='القسم / Département'),
        ),
        migrations.AddField(
            model_name='classe',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ['amphi_dep', 'salle_dep', 'laboratoire_dep']}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع المكان / Type de lieu'),
        ),
        migrations.AddField(
            model_name='classe',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='departement.matiere', verbose_name='المادة / Matière'),
        ),
        migrations.AddField(
            model_name='classe',
            name='niv_spe_dep_sg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='departement.nivspedep_sg', verbose_name='الطلبة / Étudiants (Niveau-Spécialité-Section/Groupe)'),
        ),
        migrations.AddField(
            model_name='classe',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='commun.semestre', verbose_name='السداسي / Semestre'),
        ),
        migrations.AddField(
            model_name='ens_dep',
            name='annee_univ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_ens_dep', to='commun.anneeuniversitaire', verbose_name='السنة الجامعية / Année universitaire'),
        ),
        migrations.AddField(
            model_name='ens_dep',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_enseignant', to='departement.departement', verbose_name='القسم / Département'),
        ),
        migrations.AddField(
            model_name='ens_dep',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_departement', to='enseignant.enseignant', verbose_name='الأستاذ / Enseignant'),
        ),
        migrations.AddField(
            model_name='classe',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='affectation.ens_dep', verbose_name='الأستاذ / Enseignant'),
        ),
        migrations.AddField(
            model_name='etudiantsousgroupe',
            name='affecte_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_etudiants_sg', to='enseignant.enseignant', verbose_name='أُسند بواسطة / Affecté par'),
        ),
        migrations.AddField(
            model_name='etudiantsousgroupe',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_sous_groupes', to='etudiant.etudiant', verbose_name='الطالب / Étudiant'),
        ),
        migrations.AddField(
            model_name='gestion_etu_classe',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gestion_etudiants', to='affectation.classe', verbose_name='الحصة / Classe'),
        ),
        migrations.AddField(
            model_name='gestion_etu_classe',
            name='etudiant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gestion_classes', to='etudiant.etudiant', verbose_name='الطالب / Étudiant'),
        ),
        migrations.AddField(
            model_name='laboratoire_dep',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_laboratoire', to='departement.departement', verbose_name='القسم / Département'),
        ),
        migrations.AddField(
            model_name='laboratoire_dep',
            name='laboratoire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_departement', to='commun.laboratoire', verbose_name='المخبر / Laboratoire'),
        ),
        migrations.AddField(
            model_name='salle_dep',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_salle', to='departement.departement', verbose_name='القسم / Département'),
        ),
        migrations.AddField(
            model_name='salle_dep',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_departement', to='commun.salle', verbose_name='القاعة / Salle'),
        ),
        migrations.AddField(
            model_name='seance',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seances_classe', to='affectation.classe', verbose_name='الفصل / Classe'),
        ),
        migrations.AddField(
            model_name='abs_etu_seance',
            name='seance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences_etudiants_seance', to='affectation.seance', verbose_name='الحصة / Séance'),
        ),
        migrations.AddField(
            model_name='sousgroupe',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_groupes_crees', to='enseignant.enseignant', verbose_name='أنشأ بواسطة / Créé par'),
        ),
        migrations.AddField(
            model_name='sousgroupe',
            name='groupe_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_groupes', to='departement.nivspedep_sg', verbose_name='المجموعة الأصلية / Groupe principal'),
        ),
        migrations.AddField(
            model_name='seance',
            name='sous_groupe_unique',
            field=models.ForeignKey(blank=True, help_text="يُستخدم عند اختيار 'مجموعة فرعية' / Utilisé pour un seul sous-groupe", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seances_sous_groupe_unique', to='affectation.sousgroupe', verbose_name='المجموعة الفرعية / Sous-groupe'),
        ),
        migrations.AddField(
            model_name='seance',
            name='sous_groupes_multiples',
            field=models.ManyToManyField(blank=True, help_text="يُستخدم عند اختيار 'عدة مجموعات فرعية' / Utilisé pour plusieurs sous-groupes", related_name='seances_sous_groupes_multiples', to='affectation.sousgroupe', verbose_name='المجموعات الفرعية المتعددة / Sous-groupes multiples'),
        ),
        migrations.AddField(
            model_name='etudiantsousgroupe',
            name='sous_groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants_affectes', to='affectation.sousgroupe', verbose_name='المجموعة الفرعية / Sous-groupe'),
        ),
        migrations.AddField(
            model_name='abs_etu_seance',
            name='sous_groupe_concerne',
            field=models.ForeignKey(blank=True, help_text="المجموعة الفرعية التي ينتمي إليها الطالب في هذه الحصة / Sous-groupe de l'étudiant pour cette séance", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences_sous_groupe', to='affectation.sousgroupe', verbose_name='المجموعة الفرعية المعنية / Sous-groupe concerné'),
        ),
        migrations.AddIndex(
            model_name='amphi_dep',
            index=models.Index(fields=['amphi', 'departement'], name='affectation_amphi_i_34637a_idx'),
        ),
        migrations.AddIndex(
            model_name='amphi_dep',
            index=models.Index(fields=['est_actif'], name='affectation_est_act_99df4a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='amphi_dep',
            unique_together={('amphi', 'departement')},
        ),
        migrations.AddIndex(
            model_name='ens_dep',
            index=models.Index(fields=['enseignant', 'annee_univ'], name='affectation_enseign_7b89b9_idx'),
        ),
        migrations.AddIndex(
            model_name='ens_dep',
            index=models.Index(fields=['departement', 'annee_univ'], name='affectation_departe_e07f6a_idx'),
        ),
        migrations.AddIndex(
            model_name='ens_dep',
            index=models.Index(fields=['statut'], name='affectation_statut_d1c688_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ens_dep',
            unique_together={('enseignant', 'departement', 'annee_univ')},
        ),
        migrations.AddIndex(
            model_name='classe',
            index=models.Index(fields=['semestre', 'jour', 'temps'], name='affectation_semestr_3bd8cb_idx'),
        ),
        migrations.AddIndex(
            model_name='classe',
            index=models.Index(fields=['enseignant', 'semestre'], name='affectation_enseign_9f1284_idx'),
        ),
        migrations.AddIndex(
            model_name='classe',
            index=models.Index(fields=['matiere', 'semestre'], name='affectation_matiere_e5c79c_idx'),
        ),
        migrations.AddIndex(
            model_name='classe',
            index=models.Index(fields=['niv_spe_dep_sg', 'semestre'], name='affectation_niv_spe_17b470_idx'),
        ),
        migrations.AddIndex(
            model_name='classe',
            index=models.Index(fields=['content_type', 'object_id'], name='affectation_content_1a1721_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('semestre', 'matiere', 'enseignant', 'niv_spe_dep_sg', 'jour', 'temps')},
        ),
        migrations.AddIndex(
            model_name='gestion_etu_classe',
            index=models.Index(fields=['classe', 'validee_par_enseignant'], name='affectation_classe__f33ba7_idx'),
        ),
        migrations.AddIndex(
            model_name='gestion_etu_classe',
            index=models.Index(fields=['etudiant', 'note_finale'], name='affectation_etudian_8ef309_idx'),
        ),
        migrations.AddIndex(
            model_name='gestion_etu_classe',
            index=models.Index(fields=['classe', 'note_finale'], name='affectation_classe__8f0086_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gestion_etu_classe',
            unique_together={('classe', 'etudiant')},
        ),
        migrations.AddIndex(
            model_name='laboratoire_dep',
            index=models.Index(fields=['laboratoire', 'departement'], name='affectation_laborat_32fd53_idx'),
        ),
        migrations.AddIndex(
            model_name='laboratoire_dep',
            index=models.Index(fields=['est_actif'], name='affectation_est_act_8bb073_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='laboratoire_dep',
            unique_together={('laboratoire', 'departement')},
        ),
        migrations.AddIndex(
            model_name='salle_dep',
            index=models.Index(fields=['salle', 'departement'], name='affectation_salle_i_fef4fe_idx'),
        ),
        migrations.AddIndex(
            model_name='salle_dep',
            index=models.Index(fields=['est_actif'], name='affectation_est_act_d02c4e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salle_dep',
            unique_together={('salle', 'departement')},
        ),
        migrations.AddIndex(
            model_name='sousgroupe',
            index=models.Index(fields=['groupe_principal', 'actif'], name='affectation_groupe__785b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='sousgroupe',
            index=models.Index(fields=['actif', 'ordre_affichage'], name='affectation_actif_a71536_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sousgroupe',
            unique_together={('groupe_principal', 'nom')},
        ),
        migrations.AddIndex(
            model_name='seance',
            index=models.Index(fields=['classe', 'date'], name='affectation_classe__3c2f3d_idx'),
        ),
        migrations.AddIndex(
            model_name='seance',
            index=models.Index(fields=['type_audience'], name='affectation_type_au_286530_idx'),
        ),
        migrations.AddIndex(
            model_name='seance',
            index=models.Index(fields=['fait', 'annuler'], name='affectation_fait_6ed33d_idx'),
        ),
        migrations.AddConstraint(
            model_name='seance',
            constraint=models.UniqueConstraint(fields=('classe', 'date', 'temps'), name='unique_seance_par_classe_date_temps'),
        ),
        migrations.AddIndex(
            model_name='etudiantsousgroupe',
            index=models.Index(fields=['sous_groupe', 'actif'], name='affectation_sous_gr_c4d91d_idx'),
        ),
        migrations.AddIndex(
            model_name='etudiantsousgroupe',
            index=models.Index(fields=['etudiant', 'actif'], name='affectation_etudian_f06729_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='etudiantsousgroupe',
            unique_together={('etudiant', 'sous_groupe')},
        ),
        migrations.AddIndex(
            model_name='abs_etu_seance',
            index=models.Index(fields=['seance', 'present'], name='affectation_seance__027d7a_idx'),
        ),
        migrations.AddIndex(
            model_name='abs_etu_seance',
            index=models.Index(fields=['etudiant', 'present'], name='affectation_etudian_19171a_idx'),
        ),
        migrations.AddIndex(
            model_name='abs_etu_seance',
            index=models.Index(fields=['sous_groupe_concerne'], name='affectation_sous_gr_79743b_idx'),
        ),
        migrations.AddConstraint(
            model_name='abs_etu_seance',
            constraint=models.UniqueConstraint(fields=('seance', 'etudiant'), name='unique_absence_par_seance_etudiant'),
        ),
    ]
