# Generated by Django 5.2.9 on 2025-12-10 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affectation', '0002_ens_dep_est_actif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ens_dep',
            name='est_inscrit',
        ),
    ]
