# Generated by Django 5.2.18 on 2026-10-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affectation', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='temps',
            field=models.CharField(choices=[('08:00-09:30', 'الحصة الأولى 08:00-09:30'), ('09:40-11:10', 'الحصة الثانية 09:40-11:10'), ('11:20-12:50', 'الحصة الثالثة 11:20-12:50'), ('13:10-14:40', 'الحصة الرابعة 13:10-14:40'), ('14:50-16:20', 'الحصة الخامسة 14:50-16:20'), ('16:30-18:00', 'الحصة السادسة 16:30-18:00'), ('18:00-19:30', 'الحصة السابعة 18:00-19:30'), ('19:40-21:10', 'الحصة الثامنة 19:40-21:10')], max_length=20, verbose_name='وقت الحصة / Créneau horaire'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='type',
            field=models.CharField(choices=[('Cours', 'محاضرة / Cours'), ('TD', 'أعمال موجهة / TD'), ('TP', 'أعمال تطبيقية / TP'), ('Sortie Scientifique', 'خرجة علمية / Sortie Scientifique')], max_length=30, verbose_name='نوع الحصة / Type de séance'),
        ),
        migrations.AlterField(
            model_name='ens_dep',
            name='nbrClas_SS_in_Dep_S1',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='عدد حصص الخرجة العلمية داخل القسم - س1 / Nb sorties scientifiques dans dép. S1'),
        ),
        migrations.AlterField(
            model_name='ens_dep',
            name='nbrClas_SS_in_Dep_S2',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='عدد حصص الخرجة العلمية داخل القسم - س2 / Nb sorties scientifiques dans dép. S2'),
        ),
        migrations.AlterField(
            model_name='ens_dep',
            name='nbrClas_SS_out_Dep_S1',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='عدد حصص الخرجة العلمية خارج القسم - س1 / Nb sorties scientifiques hors dép. S1'),
        ),
        migrations.AlterField(
            model_name='ens_dep',
            name='nbrClas_SS_out_Dep_S2',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='عدد حصص الخرجة العلمية خارج القسم - س2 / Nb sorties scientifiques hors dép. S2'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='temps',
            field=models.CharField(choices=[('08:00-09:30', 'الحصة الأولى 08:00-09:30'), ('09:40-11:10', 'الحصة الثانية 09:40-11:10'), ('11:20-12:50', 'الحصة الثالثة 11:20-12:50'), ('13:10-14:40', 'الحصة الرابعة 13:10-14:40'), ('14:50-16:20', 'الحصة الخامسة 14:50-16:20'), ('16:30-18:00', 'الحصة السادسة 16:30-18:00'), ('18:00-19:30', 'الحصة السابعة 18:00-19:30'), ('19:40-21:10', 'الحصة الثامنة 19:40-21:10')], default='08:00-09:30', max_length=20, verbose_name='وقت الحصة / Créneau horaire'),
        ),
    ]
