# Generated by Django 5.2.9 on 2025-12-11 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affectation', '0003_remove_ens_dep_est_inscrit'),
        ('commun', '0004_alter_identification_options_and_more'),
        ('departement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amphi_Dep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء / Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل / Date de modification')),
                ('observation', models.TextField(blank=True, default='', verbose_name='الملاحظة / Observation')),
                ('semestre_1', models.BooleanField(default=True, verbose_name='السداسي الأول / Semestre 1')),
                ('semestre_2', models.BooleanField(default=True, verbose_name='السداسي الثاني / Semestre 2')),
                ('est_actif', models.BooleanField(default=True, verbose_name='نشط / Actif')),
                ('amphi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_departement', to='commun.amphi', verbose_name='المدرج / Amphithéâtre')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_amphi', to='departement.departement', verbose_name='القسم / Département')),
            ],
            options={
                'verbose_name': 'تخصيص مدرج-قسم / Affectation Amphi-Département',
                'verbose_name_plural': 'تخصيصات مدرج-قسم / Affectations Amphi-Département',
                'ordering': ['departement__code', 'amphi__numero'],
                'indexes': [models.Index(fields=['amphi', 'departement'], name='affectation_amphi_i_34637a_idx'), models.Index(fields=['est_actif'], name='affectation_est_act_99df4a_idx')],
                'unique_together': {('amphi', 'departement')},
            },
        ),
        migrations.CreateModel(
            name='Laboratoire_Dep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء / Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل / Date de modification')),
                ('observation', models.TextField(blank=True, default='', verbose_name='الملاحظة / Observation')),
                ('semestre_1', models.BooleanField(default=True, verbose_name='السداسي الأول / Semestre 1')),
                ('semestre_2', models.BooleanField(default=True, verbose_name='السداسي الثاني / Semestre 2')),
                ('est_actif', models.BooleanField(default=True, verbose_name='نشط / Actif')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_laboratoire', to='departement.departement', verbose_name='القسم / Département')),
                ('laboratoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_departement', to='commun.laboratoire', verbose_name='المخبر / Laboratoire')),
            ],
            options={
                'verbose_name': 'تخصيص مخبر-قسم / Affectation Labo-Département',
                'verbose_name_plural': 'تخصيصات مخبر-قسم / Affectations Labo-Département',
                'ordering': ['departement__code', 'laboratoire__numero'],
                'indexes': [models.Index(fields=['laboratoire', 'departement'], name='affectation_laborat_32fd53_idx'), models.Index(fields=['est_actif'], name='affectation_est_act_8bb073_idx')],
                'unique_together': {('laboratoire', 'departement')},
            },
        ),
        migrations.CreateModel(
            name='Salle_Dep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء / Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل / Date de modification')),
                ('observation', models.TextField(blank=True, default='', verbose_name='الملاحظة / Observation')),
                ('semestre_1', models.BooleanField(default=True, verbose_name='السداسي الأول / Semestre 1')),
                ('semestre_2', models.BooleanField(default=True, verbose_name='السداسي الثاني / Semestre 2')),
                ('est_actif', models.BooleanField(default=True, verbose_name='نشط / Actif')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_salle', to='departement.departement', verbose_name='القسم / Département')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_departement', to='commun.salle', verbose_name='القاعة / Salle')),
            ],
            options={
                'verbose_name': 'تخصيص قاعة-قسم / Affectation Salle-Département',
                'verbose_name_plural': 'تخصيصات قاعة-قسم / Affectations Salle-Département',
                'ordering': ['departement__code', 'salle__numero'],
                'indexes': [models.Index(fields=['salle', 'departement'], name='affectation_salle_i_fef4fe_idx'), models.Index(fields=['est_actif'], name='affectation_est_act_d02c4e_idx')],
                'unique_together': {('salle', 'departement')},
            },
        ),
    ]
