# Generated by Django 5.2.9 on 2025-12-11 12:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affectation', '0005_classe'),
        ('departement', '0001_initial'),
        ('enseignant', '0008_alter_enseignant_est_inscrit'),
        ('etudiant', '0004_alter_etudiant_est_inscrit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abs_Etu_Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء / Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل / Date de modification')),
                ('observation', models.TextField(blank=True, default='', verbose_name='الملاحظة / Observation')),
                ('present', models.BooleanField(default=False, verbose_name='حضور الطالب / Présent')),
                ('justifiee', models.BooleanField(default=False, verbose_name='غياب مبرر / Absence justifiée')),
                ('participation', models.BooleanField(default=False, verbose_name='مشاركة في الحصة / Participation')),
                ('points_sup_seance', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=3, verbose_name='نقطة + / Points bonus')),
                ('obs', models.TextField(blank=True, verbose_name='ملاحظة / Observation')),
                ('type_audience_lors_creation', models.CharField(blank=True, help_text='لحفظ نوع الجمهور عند إنشاء الغياب / Pour historique', max_length=20, verbose_name='نوع الجمهور عند الإنشاء / Type audience à la création')),
            ],
            options={
                'verbose_name': 'حضور/غياب طالب-حصة / Présence Étudiant-Séance',
                'verbose_name_plural': 'حضور/غياب طلاب-حصص / Présences Étudiants-Séances',
                'ordering': ['seance', 'etudiant__nom_ar'],
            },
        ),
        migrations.CreateModel(
            name='EtudiantSousGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء / Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل / Date de modification')),
                ('observation', models.TextField(blank=True, default='', verbose_name='الملاحظة / Observation')),
                ('date_affectation', models.DateTimeField(auto_now_add=True, verbose_name="تاريخ التعيين / Date d'affectation")),
                ('actif', models.BooleanField(default=True, verbose_name='نشط / Actif')),
                ('ordre_dans_groupe', models.PositiveIntegerField(default=1, help_text="ترتيب الطالب داخل المجموعة الفرعية / Ordre de l'étudiant dans le sous-groupe", verbose_name='الترتيب في المجموعة / Ordre dans le groupe')),
            ],
            options={
                'verbose_name': 'طالب - مجموعة فرعية / Étudiant-Sous-groupe',
                'verbose_name_plural': 'طلاب - مجموعات فرعية / Étudiants-Sous-groupes',
                'ordering': ['sous_groupe', 'ordre_dans_groupe', 'etudiant__nom_ar'],
            },
        ),
        migrations.CreateModel(
            name='Gestion_Etu_Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء / Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل / Date de modification')),
                ('observation', models.TextField(blank=True, default='', verbose_name='الملاحظة / Observation')),
                ('nbr_absence', models.PositiveIntegerField(default=0, help_text="العدد الإجمالي للغيابات / Nombre total d'absences", verbose_name='عدد الغيابات / Nb absences')),
                ('nbr_absence_justifiee', models.PositiveIntegerField(default=0, help_text='الغيابات المبررة بوثائق رسمية / Absences justifiées par documents', verbose_name='عدد الغيابات المبررة / Nb absences justifiées')),
                ('nbr_seances_totales', models.PositiveIntegerField(default=0, help_text='يتم حسابه تلقائياً / Calculé automatiquement', verbose_name='العدد الإجمالي للحصص / Nb total séances')),
                ('total_sup_seance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='نقاط إضافية للمشاركة المتميزة (حد أقصى 3 نقاط) / Max 3 points', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('3.00'))], verbose_name='نقاط إضافية للمشاركة / Points bonus participation')),
                ('note_presence', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='محسوبة تلقائياً حسب نسبة الحضور / Calculée auto selon présence', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))], verbose_name='نقطة الحضور / Note présence')),
                ('note_participe_HW', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='تقييم المشاركة والواجبات المنزلية / Évaluation participation et devoirs', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))], verbose_name='نقطة المشاركة والأعمال المنزلية / Note participation/devoirs')),
                ('note_controle_1', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='نقطة الامتحان 1 / Note du contrôle 1', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))], verbose_name='نقطة الإمتحان 1 / Note contrôle 1')),
                ('note_controle_2', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='نقطة الامتحان 2 / Note du contrôle 2', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))], verbose_name='نقطة الإمتحان 2 / Note contrôle 2')),
                ('note_finale', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='النقطة النهائية محسوبة تلقائياً / Note finale calculée auto', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('20.00'))], verbose_name='النقطة النهائية / Note finale')),
                ('date_derniere_maj', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث / Dernière mise à jour')),
                ('validee_par_enseignant', models.BooleanField(default=False, help_text="هل تم تأكيد النقاط من طرف الأستاذ؟ / Notes confirmées par l'enseignant?", verbose_name='تم التصديق من طرف الأستاذ / Validé par enseignant')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التصديق / Date validation')),
                ('obs', models.TextField(blank=True, default='', help_text="ملاحظات الأستاذ حول أداء الطالب / Observations de l'enseignant", null=True, verbose_name='الملاحظة / Observation')),
            ],
            options={
                'verbose_name': 'إدارة طالب-حصة / Gestion Étudiant-Classe',
                'verbose_name_plural': 'إدارة طلاب-حصص / Gestions Étudiants-Classes',
                'ordering': ['classe', 'etudiant__nom_ar', 'etudiant__prenom_ar'],
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء / Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل / Date de modification')),
                ('observation', models.TextField(blank=True, default='', verbose_name='الملاحظة / Observation')),
                ('intitule', models.CharField(blank=True, default='لم أقم بالتدريس', max_length=200, null=True, verbose_name='عنوان الحصة / Intitulé')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الحصة / Date')),
                ('temps', models.CharField(choices=[('08:00-09:30', 'الحصة الأولى 08:00-09:30'), ('09:40-11:10', 'الحصة الثانية 09:40-11:10'), ('11:20-12:50', 'الحصة الثالثة 11:20-12:50'), ('13:10-14:40', 'الحصة الرابعة 13:10-14:40'), ('14:50-16:20', 'الحصة الخامسة 14:50-16:20'), ('16:30-18:00', 'الحصة السادسة 16:30-18:00')], default='08:00-09:30', max_length=20, verbose_name='وقت الحصة / Créneau horaire')),
                ('fait', models.BooleanField(default=False, verbose_name='تمت الحصة / Séance effectuée')),
                ('remplacer', models.BooleanField(default=False, verbose_name='حصة تعويضية / Séance de remplacement')),
                ('annuler', models.BooleanField(default=False, verbose_name='الحصة ملغاة / Séance annulée')),
                ('list_abs_etudiant_generee', models.BooleanField(default=False, verbose_name='تم إنشاء قائمة الغيابات / Liste absences générée')),
                ('obs', models.TextField(blank=True, verbose_name='الملاحظة / Observation')),
                ('type_audience', models.CharField(choices=[('groupe_complet', 'المجموعة كاملة / Groupe complet'), ('sous_groupe', 'مجموعة فرعية / Sous-groupe'), ('multi_sous_groupes', 'عدة مجموعات فرعية / Multi sous-groupes')], default='groupe_complet', help_text='تحديد من سيحضر هذه الحصة / Définir qui assiste à cette séance', max_length=20, verbose_name="نوع الجمهور / Type d'audience")),
                ('nb_etudiants_concernes', models.PositiveIntegerField(default=0, help_text='يتم حسابه تلقائياً / Calculé automatiquement', verbose_name='عدد الطلاب المعنيين / Nb étudiants concernés')),
            ],
            options={
                'verbose_name': 'حصة / Séance',
                'verbose_name_plural': 'حصص / Séances',
                'ordering': ['-date', 'temps'],
            },
        ),
        migrations.CreateModel(
            name='SousGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء / Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل / Date de modification')),
                ('observation', models.TextField(blank=True, default='', verbose_name='الملاحظة / Observation')),
                ('nom', models.CharField(help_text='مثال: A, B, 1, 2 / Ex: A, B, 1, 2', max_length=50, verbose_name='اسم المجموعة الفرعية / Nom du sous-groupe')),
                ('nom_complet', models.CharField(blank=True, help_text='سيتم إنشاؤه تلقائياً / Généré automatiquement', max_length=100, verbose_name='الاسم الكامل / Nom complet')),
                ('description', models.TextField(blank=True, verbose_name='الوصف / Description')),
                ('effectif', models.PositiveIntegerField(default=0, verbose_name='عدد الطلاب / Effectif')),
                ('actif', models.BooleanField(default=True, verbose_name='نشط / Actif')),
                ('ordre_affichage', models.PositiveIntegerField(default=1, help_text="ترتيب عرض المجموعة الفرعية / Ordre d'affichage du sous-groupe", verbose_name="ترتيب العرض / Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'مجموعة فرعية / Sous-groupe',
                'verbose_name_plural': 'مجموعات فرعية / Sous-groupes',
                'ordering': ['groupe_principal', 'ordre_affichage', 'nom'],
            },
        ),
        migrations.RenameIndex(
            model_name='classe',
            new_name='affectation_semestr_3bd8cb_idx',
            old_name='affectation_semestr_b1c2d3_idx',
        ),
        migrations.RenameIndex(
            model_name='classe',
            new_name='affectation_enseign_9f1284_idx',
            old_name='affectation_enseign_a4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='classe',
            new_name='affectation_matiere_e5c79c_idx',
            old_name='affectation_matiere_d7e8f9_idx',
        ),
        migrations.RenameIndex(
            model_name='classe',
            new_name='affectation_niv_spe_17b470_idx',
            old_name='affectation_niv_spe_g0h1i2_idx',
        ),
        migrations.RenameIndex(
            model_name='classe',
            new_name='affectation_content_1a1721_idx',
            old_name='affectation_content_j3k4l5_idx',
        ),
        migrations.AddField(
            model_name='abs_etu_seance',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absences_etudiant', to='etudiant.etudiant', verbose_name='الطالب / Étudiant'),
        ),
        migrations.AddField(
            model_name='etudiantsousgroupe',
            name='affecte_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_etudiants_sg', to='enseignant.enseignant', verbose_name='أُسند بواسطة / Affecté par'),
        ),
        migrations.AddField(
            model_name='etudiantsousgroupe',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_sous_groupes', to='etudiant.etudiant', verbose_name='الطالب / Étudiant'),
        ),
        migrations.AddField(
            model_name='gestion_etu_classe',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gestion_etudiants', to='affectation.classe', verbose_name='الحصة / Classe'),
        ),
        migrations.AddField(
            model_name='gestion_etu_classe',
            name='etudiant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gestion_classes', to='etudiant.etudiant', verbose_name='الطالب / Étudiant'),
        ),
        migrations.AddField(
            model_name='seance',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seances_classe', to='affectation.classe', verbose_name='الفصل / Classe'),
        ),
        migrations.AddField(
            model_name='abs_etu_seance',
            name='seance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences_etudiants_seance', to='affectation.seance', verbose_name='الحصة / Séance'),
        ),
        migrations.AddField(
            model_name='sousgroupe',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_groupes_crees', to='enseignant.enseignant', verbose_name='أنشأ بواسطة / Créé par'),
        ),
        migrations.AddField(
            model_name='sousgroupe',
            name='groupe_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_groupes', to='departement.nivspedep_sg', verbose_name='المجموعة الأصلية / Groupe principal'),
        ),
        migrations.AddField(
            model_name='seance',
            name='sous_groupe_unique',
            field=models.ForeignKey(blank=True, help_text="يُستخدم عند اختيار 'مجموعة فرعية' / Utilisé pour un seul sous-groupe", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seances_sous_groupe_unique', to='affectation.sousgroupe', verbose_name='المجموعة الفرعية / Sous-groupe'),
        ),
        migrations.AddField(
            model_name='seance',
            name='sous_groupes_multiples',
            field=models.ManyToManyField(blank=True, help_text="يُستخدم عند اختيار 'عدة مجموعات فرعية' / Utilisé pour plusieurs sous-groupes", related_name='seances_sous_groupes_multiples', to='affectation.sousgroupe', verbose_name='المجموعات الفرعية المتعددة / Sous-groupes multiples'),
        ),
        migrations.AddField(
            model_name='etudiantsousgroupe',
            name='sous_groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants_affectes', to='affectation.sousgroupe', verbose_name='المجموعة الفرعية / Sous-groupe'),
        ),
        migrations.AddField(
            model_name='abs_etu_seance',
            name='sous_groupe_concerne',
            field=models.ForeignKey(blank=True, help_text="المجموعة الفرعية التي ينتمي إليها الطالب في هذه الحصة / Sous-groupe de l'étudiant pour cette séance", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences_sous_groupe', to='affectation.sousgroupe', verbose_name='المجموعة الفرعية المعنية / Sous-groupe concerné'),
        ),
        migrations.AddIndex(
            model_name='gestion_etu_classe',
            index=models.Index(fields=['classe', 'validee_par_enseignant'], name='affectation_classe__f33ba7_idx'),
        ),
        migrations.AddIndex(
            model_name='gestion_etu_classe',
            index=models.Index(fields=['etudiant', 'note_finale'], name='affectation_etudian_8ef309_idx'),
        ),
        migrations.AddIndex(
            model_name='gestion_etu_classe',
            index=models.Index(fields=['classe', 'note_finale'], name='affectation_classe__8f0086_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gestion_etu_classe',
            unique_together={('classe', 'etudiant')},
        ),
        migrations.AddIndex(
            model_name='sousgroupe',
            index=models.Index(fields=['groupe_principal', 'actif'], name='affectation_groupe__785b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='sousgroupe',
            index=models.Index(fields=['actif', 'ordre_affichage'], name='affectation_actif_a71536_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sousgroupe',
            unique_together={('groupe_principal', 'nom')},
        ),
        migrations.AddIndex(
            model_name='seance',
            index=models.Index(fields=['classe', 'date'], name='affectation_classe__3c2f3d_idx'),
        ),
        migrations.AddIndex(
            model_name='seance',
            index=models.Index(fields=['type_audience'], name='affectation_type_au_286530_idx'),
        ),
        migrations.AddIndex(
            model_name='seance',
            index=models.Index(fields=['fait', 'annuler'], name='affectation_fait_6ed33d_idx'),
        ),
        migrations.AddConstraint(
            model_name='seance',
            constraint=models.UniqueConstraint(fields=('classe', 'date', 'temps'), name='unique_seance_par_classe_date_temps'),
        ),
        migrations.AddIndex(
            model_name='etudiantsousgroupe',
            index=models.Index(fields=['sous_groupe', 'actif'], name='affectation_sous_gr_c4d91d_idx'),
        ),
        migrations.AddIndex(
            model_name='etudiantsousgroupe',
            index=models.Index(fields=['etudiant', 'actif'], name='affectation_etudian_f06729_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='etudiantsousgroupe',
            unique_together={('etudiant', 'sous_groupe')},
        ),
        migrations.AddIndex(
            model_name='abs_etu_seance',
            index=models.Index(fields=['seance', 'present'], name='affectation_seance__027d7a_idx'),
        ),
        migrations.AddIndex(
            model_name='abs_etu_seance',
            index=models.Index(fields=['etudiant', 'present'], name='affectation_etudian_19171a_idx'),
        ),
        migrations.AddIndex(
            model_name='abs_etu_seance',
            index=models.Index(fields=['sous_groupe_concerne'], name='affectation_sous_gr_79743b_idx'),
        ),
        migrations.AddConstraint(
            model_name='abs_etu_seance',
            constraint=models.UniqueConstraint(fields=('seance', 'etudiant'), name='unique_absence_par_seance_etudiant'),
        ),
    ]
